name: Practicheskaya15CHECKAPI

on:
  push: 
    branches:
      - main 
jobs:
  check-api: 
    runs-on: windows-latest 

    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v2 

    - name: .NET Core 
      uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: '6.0.x' 
  
    - name: Restore dependencies 
      run: dotnet restore 

    - name: Download NuGet package 
      run: dotnet add Practa15Obrazcova/Practa15Obrazcova.csproj package Microsoft.CodeAnalysis.NetAnalyzers --version 8.0.0 
    
    - name: Check api project syntacsys   
      run: dotnet build Practa15Obrazcova/Practa15Obrazcova.csproj /p:WarningLevel=6 /p:DebugType=None /p:DebugSymbols-false /p:Platform="Any CPU" /p:TreatWarningsAsErrors=true